---
version: '3'
services:
#
# frontend proxy
#
  nginx:
    build:
      context: ./build-nginx
    restart: always
    ports:
      - 443:443
      - 80:80

#
# artifactory service
#
  artifactory:
    build:
      context: ./build-artifactory
    restart: unless-stopped
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    environment:
      - 'JF_SHARED_EXTRAJAVAOPTS=-Xms512m -Xmx12g -Xss256k -XX:+UseG1GC'
      - 'JF_ACCESS_TOMCAT_CONNECTOR_MAXTHREADS=200'
      - 'JF_ARTIFACTORY_TOMCAT_CONNECTOR_MAXTHREADS=50'

volumes:
  artifactory_data:
