---
version: '3'
services:

#
# mkcert
#
  mkcert:
    image: ghcr.io/tenzin-io/mkcert:amd64-v1
    environment:
      - 'CERT_HOSTNAME=repo'
      - 'CERT_DOMAIN=tenzin.io'
    volumes:
      - certs_data:/certs.d/

#
# frontend proxy
#
  nginx:
    build:
      context: ./build-nginx
    volumes:
      - certs_data:/etc/nginx/certs.d/
    restart: always
    ports:
      - 443:443
    depends_on:
      - mkcert

#
# artifactory service
#
  artifactory:
    build: 
      context: ./build-artifactory
    restart: unless-stopped
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    environment:
      - 'JF_SHARED_EXTRAJAVAOPTS=-Xms512m -Xmx12g -Xss256k -XX:+UseG1GC'
      - 'JF_ACCESS_TOMCAT_CONNECTOR_MAXTHREADS=200'
      - 'JF_ARTIFACTORY_TOMCAT_CONNECTOR_MAXTHREADS=50'
    depends_on:
      - nginx

volumes:
  artifactory_data:
  certs_data:
